In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [41]:
myFile = np.genfromtxt('magic04.data', dtype=None, delimiter=',', encoding=None)
myFile2 = np.genfromtxt('magic04.data', delimiter=',')
myFile3 = np.genfromtxt('magic04.data', dtype=str, delimiter=',')
print(myFile)
print(myFile2)
print(myFile3)

[( 28.7967,  16.0021, 2.6449, 0.3918, 0.1982,   27.7004,   22.011 ,  -8.2027, 40.092 ,  81.8828, 'g')
 ( 31.6036,  11.7235, 2.5185, 0.5303, 0.3773,   26.2722,   23.8238,  -9.9574,  6.3609, 205.261 , 'g')
 (162.052 , 136.031 , 4.0612, 0.0374, 0.0187,  116.741 ,  -64.858 , -45.216 , 76.96  , 256.788 , 'g')
 ...
 ( 75.4455,  47.5305, 3.4483, 0.1417, 0.0549,   -9.3561,   41.0562,  -9.4662, 30.2987, 256.5166, 'h')
 (120.5135,  76.9018, 3.9939, 0.0944, 0.0683,    5.8043,  -93.5224, -63.8389, 84.6874, 408.3166, 'h')
 (187.1814,  53.0014, 3.2093, 0.2876, 0.1539, -167.3125, -168.4558,  31.4755, 52.731 , 272.3174, 'h')]
[[ 28.7967  16.0021   2.6449 ...  40.092   81.8828      nan]
 [ 31.6036  11.7235   2.5185 ...   6.3609 205.261       nan]
 [162.052  136.031    4.0612 ...  76.96   256.788       nan]
 ...
 [ 75.4455  47.5305   3.4483 ...  30.2987 256.5166      nan]
 [120.5135  76.9018   3.9939 ...  84.6874 408.3166      nan]
 [187.1814  53.0014   3.2093 ...  52.731  272.3174      nan]]
[['28.7967

In [46]:
X = myFile2[:, 0:-1]
print(X)

y = myFile3[:, -1]
print(y)

[[ 28.7967  16.0021   2.6449 ...  -8.2027  40.092   81.8828]
 [ 31.6036  11.7235   2.5185 ...  -9.9574   6.3609 205.261 ]
 [162.052  136.031    4.0612 ... -45.216   76.96   256.788 ]
 ...
 [ 75.4455  47.5305   3.4483 ...  -9.4662  30.2987 256.5166]
 [120.5135  76.9018   3.9939 ... -63.8389  84.6874 408.3166]
 [187.1814  53.0014   3.2093 ...  31.4755  52.731  272.3174]]
g
